-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE SCHEMA "hangfire";
--> statement-breakpoint
CREATE TABLE "hangfire"."aggregatedcounter" (
	"id" bigserial PRIMARY KEY,
	"key" text NOT NULL CONSTRAINT "aggregatedcounter_key_key" UNIQUE,
	"value" bigint NOT NULL,
	"expireat" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hangfire"."counter" (
	"id" bigserial PRIMARY KEY,
	"key" text NOT NULL,
	"value" bigint NOT NULL,
	"expireat" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hangfire"."hash" (
	"id" bigserial PRIMARY KEY,
	"key" text NOT NULL,
	"field" text NOT NULL,
	"value" text,
	"expireat" timestamp with time zone,
	"updatecount" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "hash_key_field_key" UNIQUE("key","field")
);
--> statement-breakpoint
CREATE TABLE "hangfire"."job" (
	"id" bigserial PRIMARY KEY,
	"stateid" bigint,
	"statename" text,
	"invocationdata" jsonb NOT NULL,
	"arguments" jsonb NOT NULL,
	"createdat" timestamp with time zone NOT NULL,
	"expireat" timestamp with time zone,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."jobparameter" (
	"id" bigserial PRIMARY KEY,
	"jobid" bigint NOT NULL,
	"name" text NOT NULL,
	"value" text,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."jobqueue" (
	"id" bigserial PRIMARY KEY,
	"jobid" bigint NOT NULL,
	"queue" text NOT NULL,
	"fetchedat" timestamp with time zone,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."list" (
	"id" bigserial PRIMARY KEY,
	"key" text NOT NULL,
	"value" text,
	"expireat" timestamp with time zone,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."lock" (
	"resource" text NOT NULL CONSTRAINT "lock_resource_key" UNIQUE,
	"updatecount" integer DEFAULT 0 NOT NULL,
	"acquired" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hangfire"."schema" (
	"version" integer PRIMARY KEY
);
--> statement-breakpoint
CREATE TABLE "hangfire"."server" (
	"id" text PRIMARY KEY,
	"data" jsonb,
	"lastheartbeat" timestamp with time zone NOT NULL,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."set" (
	"id" bigserial PRIMARY KEY,
	"key" text NOT NULL,
	"score" double precision NOT NULL,
	"value" text NOT NULL,
	"expireat" timestamp with time zone,
	"updatecount" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "set_key_value_key" UNIQUE("key","value")
);
--> statement-breakpoint
CREATE TABLE "hangfire"."state" (
	"id" bigserial PRIMARY KEY,
	"jobid" bigint NOT NULL,
	"name" text NOT NULL,
	"reason" text,
	"createdat" timestamp with time zone NOT NULL,
	"data" jsonb,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "__EFMigrationsHistory" (
	"MigrationId" varchar(150),
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY("MigrationId")
);
--> statement-breakpoint
CREATE TABLE "AdjustingJournal" (
	"Id" serial PRIMARY KEY,
	"JournalEntryId" integer,
	"TransactionNumber" varchar,
	"EntryDate" timestamp with time zone,
	"JournalType" varchar,
	"HeaderDescription" text,
	"Status" text,
	"UserId" uuid,
	"LineId" integer,
	"AccountId" integer,
	"LineDescription" varchar,
	"Debit" numeric,
	"Credit" numeric,
	"LineOrder" integer,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "AspNetRoleClaims" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "AspNetRoleClaims_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"RoleId" uuid NOT NULL,
	"ClaimType" text,
	"ClaimValue" text,
	CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "AspNetRoles" (
	"Id" uuid,
	"Name" varchar(256),
	"NormalizedName" varchar(256),
	"ConcurrencyStamp" text,
	CONSTRAINT "PK_AspNetRoles" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "AspNetUserClaims" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "AspNetUserClaims_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"UserId" uuid NOT NULL,
	"ClaimType" text,
	"ClaimValue" text,
	CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "AspNetUserLogins" (
	"LoginProvider" text,
	"ProviderKey" text,
	"ProviderDisplayName" text,
	"UserId" uuid NOT NULL,
	CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY("LoginProvider","ProviderKey")
);
--> statement-breakpoint
CREATE TABLE "AspNetUserRoles" (
	"UserId" uuid,
	"RoleId" uuid,
	CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY("UserId","RoleId")
);
--> statement-breakpoint
CREATE TABLE "AspNetUsers" (
	"Id" uuid,
	"FullName" text,
	"UserName" varchar(256),
	"NormalizedUserName" varchar(256),
	"Email" varchar(256),
	"NormalizedEmail" varchar(256),
	"EmailConfirmed" boolean NOT NULL,
	"PasswordHash" text,
	"SecurityStamp" text,
	"ConcurrencyStamp" text,
	"PhoneNumber" text,
	"PhoneNumberConfirmed" boolean NOT NULL,
	"TwoFactorEnabled" boolean NOT NULL,
	"LockoutEnd" timestamp with time zone,
	"LockoutEnabled" boolean NOT NULL,
	"AccessFailedCount" integer NOT NULL,
	"AvatarUrl" text,
	"Bio" text,
	CONSTRAINT "PK_AspNetUsers" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "AspNetUserTokens" (
	"UserId" uuid,
	"LoginProvider" text,
	"Name" text,
	"Value" text,
	CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY("UserId","LoginProvider","Name")
);
--> statement-breakpoint
CREATE TABLE "ChartOfAccounts" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "ChartOfAccounts_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ReferenceNumber" integer NOT NULL,
	"AccountName" varchar(100) NOT NULL,
	"Type" text NOT NULL,
	"Role" text NOT NULL,
	"IsActive" boolean NOT NULL,
	"UserId" uuid NOT NULL,
	CONSTRAINT "PK_ChartOfAccounts" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "ClosingJournal" (
	"Id" serial PRIMARY KEY,
	"JournalEntryId" integer,
	"TransactionNumber" varchar,
	"EntryDate" timestamp with time zone,
	"JournalType" varchar,
	"HeaderDescription" text,
	"Status" text,
	"UserId" uuid,
	"LineId" integer,
	"AccountId" integer,
	"LineDescription" varchar,
	"Debit" numeric,
	"Credit" numeric,
	"LineOrder" integer,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "DataProtectionKeys" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "DataProtectionKeys_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"FriendlyName" text,
	"Xml" text,
	CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "GeneralJournal" (
	"Id" serial PRIMARY KEY,
	"JournalEntryId" integer,
	"TransactionNumber" varchar(255),
	"EntryDate" timestamp with time zone,
	"JournalType" varchar(255),
	"HeaderDescription" text,
	"Status" text,
	"UserId" uuid,
	"LineId" integer,
	"AccountId" integer,
	"LineDescription" varchar(255),
	"Debit" numeric,
	"Credit" numeric,
	"LineOrder" integer,
	"CreatedAt" timestamp with time zone,
	"UpdatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "GeneralLedgerPermanentAccounts" (
	"Id" serial,
	"UserId" uuid NOT NULL,
	"PeriodId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"JournalEntryId" integer NOT NULL,
	"JournalEntryLineId" integer NOT NULL,
	"EntryDate" timestamp with time zone NOT NULL,
	"TransactionNumber" varchar(255) NOT NULL,
	"LineDescription" text,
	"Debit" numeric(18,2) DEFAULT '0.00' NOT NULL,
	"Credit" numeric(18,2) DEFAULT '0.00' NOT NULL,
	"RunningBalance" numeric(18,2) DEFAULT '0.00' NOT NULL,
	CONSTRAINT "permanent_account_general_ledgers_pkey" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "GeneralLedgerTemporaryAccounts" (
	"Id" serial,
	"UserId" uuid NOT NULL,
	"PeriodId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"JournalEntryId" integer NOT NULL,
	"JournalEntryLineId" integer NOT NULL,
	"EntryDate" timestamp with time zone NOT NULL,
	"TransactionNumber" varchar(255) NOT NULL,
	"LineDescription" text,
	"Debit" numeric(18,2) DEFAULT '0.00' NOT NULL,
	"Credit" numeric(18,2) DEFAULT '0.00' NOT NULL,
	"RunningBalance" numeric(18,2) DEFAULT '0.00' NOT NULL,
	CONSTRAINT "temporary_account_general_ledgers_pkey" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "JournalEntries" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "JournalEntries_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"JournalType" varchar(50) NOT NULL,
	"EntryDate" timestamp with time zone NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"TransactionNumber" varchar(30) NOT NULL,
	"UserId" uuid NOT NULL,
	"UpdatedAt" timestamp with time zone,
	"Description" text,
	"Status" text DEFAULT 0,
	CONSTRAINT "PK_JournalEntries" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "JournalEntryLines" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "JournalEntryLines_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"JournalEntryId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"LineDescription" varchar(250),
	"Debit" numeric(18,2) NOT NULL,
	"Credit" numeric(18,2) NOT NULL,
	"LineOrder" integer NOT NULL,
	CONSTRAINT "PK_JournalEntryLines" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "LoginActivities" (
	"Id" uuid,
	"UserId" uuid NOT NULL,
	"ActivityType" text NOT NULL,
	"IsSuccess" boolean NOT NULL,
	"Device" text NOT NULL,
	"Browser" text NOT NULL,
	"OperatingSystem" text NOT NULL,
	"IpAddress" text NOT NULL,
	"Country" text NOT NULL,
	"UserAgent" text NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "PK_LoginActivities" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "Notifications" (
	"Id" uuid,
	"UserId" uuid NOT NULL,
	"Title" text NOT NULL,
	"Message" text NOT NULL,
	"Type" text NOT NULL,
	"IsRead" boolean NOT NULL,
	"TargetUrl" text,
	"CreatedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "PK_Notifications" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "Periods" (
	"Id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "Periods_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"PeriodName" varchar(50) NOT NULL,
	"StartDate" timestamp with time zone NOT NULL,
	"EndDate" timestamp with time zone NOT NULL,
	"IsClosed" boolean DEFAULT false NOT NULL,
	"IsSelected" boolean DEFAULT false NOT NULL,
	"UserId" uuid NOT NULL,
	CONSTRAINT "PK_Periods" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "RecoveryCodes" (
	"Id" uuid PRIMARY KEY,
	"UserId" uuid NOT NULL,
	"CodeHash" varchar(255) NOT NULL,
	"Used" boolean DEFAULT false NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL,
	"UsedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "SecuritySettings" (
	"UserId" uuid PRIMARY KEY,
	"EmailVerified" boolean DEFAULT false NOT NULL,
	"TwoFactorEnabled" boolean DEFAULT false NOT NULL,
	"LoginNotificationEnabled" boolean DEFAULT true NOT NULL,
	"SessionTimeoutMinutes" integer DEFAULT 30 NOT NULL,
	"UpdatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "TransactionCounters" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "TransactionCounters_Id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"UserId" uuid NOT NULL,
	"CounterKey" varchar(10) NOT NULL,
	"LastSequence" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "TrialBalance" (
	"Id" serial,
	"UserId" uuid NOT NULL,
	"PeriodId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"EndingDebit" numeric(18,2) DEFAULT '0' NOT NULL,
	"EndingCredit" numeric(18,2) DEFAULT '0' NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "TrialBalanceUnadjusted_pkey" PRIMARY KEY("Id"),
	CONSTRAINT "UQ_TB_Unadjusted_User_Period_Account" UNIQUE("UserId","PeriodId","AccountId")
);
--> statement-breakpoint
CREATE TABLE "TrialBalanceAdjusted" (
	"Id" serial PRIMARY KEY,
	"UserId" uuid NOT NULL,
	"PeriodId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"EndingDebit" numeric(18,2) DEFAULT '0' NOT NULL,
	"EndingCredit" numeric(18,2) DEFAULT '0' NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "UQ_TB_Adjusted_User_Period_Account" UNIQUE("UserId","PeriodId","AccountId")
);
--> statement-breakpoint
CREATE TABLE "TrialBalancePostClosing" (
	"Id" serial PRIMARY KEY,
	"UserId" uuid NOT NULL,
	"PeriodId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"EndingDebit" numeric(18,2) DEFAULT '0' NOT NULL,
	"EndingCredit" numeric(18,2) DEFAULT '0' NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "UQ_TB_PostClosing_User_Period_Account" UNIQUE("UserId","PeriodId","AccountId")
);
--> statement-breakpoint
CREATE TABLE "TrustedDevices" (
	"Id" uuid PRIMARY KEY,
	"UserId" uuid NOT NULL,
	"DeviceName" varchar(100) NOT NULL,
	"DeviceIdentifier" varchar(255) NOT NULL CONSTRAINT "TrustedDevices_DeviceIdentifier_key" UNIQUE,
	"Browser" varchar(100) NOT NULL,
	"OperatingSystem" varchar(100) NOT NULL,
	"IsTrusted" boolean DEFAULT true NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL,
	"LastUsedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "UserSessions" (
	"Id" uuid,
	"UserId" uuid NOT NULL,
	"DeviceName" text NOT NULL,
	"Browser" text NOT NULL,
	"OperatingSystem" text NOT NULL,
	"IpAddress" text NOT NULL,
	"Country" text NOT NULL,
	"UserAgent" text NOT NULL,
	"RefreshTokenHash" text NOT NULL,
	"IsActive" boolean NOT NULL,
	"IsCurrent" boolean NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL,
	"LastActivityAt" timestamp with time zone NOT NULL,
	"RevokedAt" timestamp with time zone,
	CONSTRAINT "PK_UserSessions" PRIMARY KEY("Id")
);
--> statement-breakpoint
CREATE TABLE "Worksheet" (
	"Id" serial PRIMARY KEY,
	"PeriodDate" date,
	"AccountNumber" varchar(50) NOT NULL,
	"AccountName" varchar(255) NOT NULL,
	"TrialBalanceDebit" numeric(18,2) DEFAULT '0',
	"TrialBalanceCredit" numeric(18,2) DEFAULT '0',
	"AdjustingJournalDebit" numeric(18,2) DEFAULT '0',
	"AdjustingJournalCredit" numeric(18,2) DEFAULT '0',
	"TrialBalanceAdjustedDebit" numeric(18,2) DEFAULT '0',
	"TrialBalanceAdjustedCredit" numeric(18,2) DEFAULT '0',
	"IncomeStatementDebit" numeric(18,2) DEFAULT '0',
	"IncomeStatementCredit" numeric(18,2) DEFAULT '0',
	"FinancialPositionDebit" numeric(18,2) DEFAULT '0',
	"FinancialPositionCredit" numeric(18,2) DEFAULT '0',
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE INDEX "ix_hangfire_counter_expireat" ON "hangfire"."counter" ("expireat");--> statement-breakpoint
CREATE INDEX "ix_hangfire_counter_key" ON "hangfire"."counter" ("key");--> statement-breakpoint
CREATE INDEX "ix_hangfire_hash_expireat" ON "hangfire"."hash" ("expireat");--> statement-breakpoint
CREATE INDEX "ix_hangfire_job_expireat" ON "hangfire"."job" ("expireat");--> statement-breakpoint
CREATE INDEX "ix_hangfire_job_statename" ON "hangfire"."job" ("statename");--> statement-breakpoint
CREATE INDEX "ix_hangfire_job_statename_is_not_null" ON "hangfire"."job" ("statename") WHERE (statename IS NOT NULL);--> statement-breakpoint
CREATE INDEX "ix_hangfire_jobparameter_jobidandname" ON "hangfire"."jobparameter" ("jobid","name");--> statement-breakpoint
CREATE INDEX "ix_hangfire_jobqueue_fetchedat_queue_jobid" ON "hangfire"."jobqueue" ("fetchedat" NULLS FIRST,"queue","jobid");--> statement-breakpoint
CREATE INDEX "ix_hangfire_jobqueue_jobidandqueue" ON "hangfire"."jobqueue" ("jobid","queue");--> statement-breakpoint
CREATE INDEX "ix_hangfire_jobqueue_queueandfetchedat" ON "hangfire"."jobqueue" ("queue","fetchedat");--> statement-breakpoint
CREATE INDEX "ix_hangfire_list_expireat" ON "hangfire"."list" ("expireat");--> statement-breakpoint
CREATE INDEX "ix_hangfire_set_expireat" ON "hangfire"."set" ("expireat");--> statement-breakpoint
CREATE INDEX "ix_hangfire_set_key_score" ON "hangfire"."set" ("key","score");--> statement-breakpoint
CREATE INDEX "ix_hangfire_state_jobid" ON "hangfire"."state" ("jobid");--> statement-breakpoint
CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");--> statement-breakpoint
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");--> statement-breakpoint
CREATE INDEX "idx_pagl_user_period_account" ON "GeneralLedgerPermanentAccounts" ("UserId","PeriodId","AccountId");--> statement-breakpoint
CREATE INDEX "idx_tagl_user_period_account" ON "GeneralLedgerTemporaryAccounts" ("UserId","PeriodId","AccountId");--> statement-breakpoint
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");--> statement-breakpoint
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");--> statement-breakpoint
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");--> statement-breakpoint
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");--> statement-breakpoint
CREATE INDEX "IX_ChartOfAccounts_UserId" ON "ChartOfAccounts" ("UserId");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_ChartOfAccounts_UserId_ReferenceNumber" ON "ChartOfAccounts" ("UserId","ReferenceNumber");--> statement-breakpoint
CREATE INDEX "IX_JournalEntries_UserId" ON "JournalEntries" ("UserId");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_JournalEntries_UserId_TransactionNumber" ON "JournalEntries" ("UserId","TransactionNumber");--> statement-breakpoint
CREATE INDEX "IX_JournalEntryLines_AccountId" ON "JournalEntryLines" ("AccountId");--> statement-breakpoint
CREATE INDEX "IX_JournalEntryLines_JournalEntryId" ON "JournalEntryLines" ("JournalEntryId");--> statement-breakpoint
CREATE INDEX "IX_LoginActivities_UserId_CreatedAt" ON "LoginActivities" ("UserId","CreatedAt");--> statement-breakpoint
CREATE INDEX "IX_Notifications_UserId_IsRead_CreatedAt" ON "Notifications" ("UserId","IsRead","CreatedAt");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_Periods_IsSelected_Unique" ON "Periods" ("UserId") WHERE ("IsSelected" = true);--> statement-breakpoint
CREATE INDEX "IX_Periods_UserId" ON "Periods" ("UserId");--> statement-breakpoint
CREATE INDEX "IX_RecoveryCodes_UserId" ON "RecoveryCodes" ("UserId");--> statement-breakpoint
CREATE UNIQUE INDEX "IX_TransactionCounters_UserId_CounterKey" ON "TransactionCounters" ("UserId","CounterKey");--> statement-breakpoint
CREATE INDEX "IX_TrustedDevices_UserId" ON "TrustedDevices" ("UserId");--> statement-breakpoint
CREATE INDEX "IX_UserSessions_UserId_IsActive" ON "UserSessions" ("UserId","IsActive");--> statement-breakpoint
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");--> statement-breakpoint
ALTER TABLE "JournalEntries" ADD CONSTRAINT "FK_JournalEntries_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "AspNetRoleClaims" ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "JournalEntryLines" ADD CONSTRAINT "FK_JournalEntryLines_ChartOfAccounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "ChartOfAccounts"("Id") ON DELETE RESTRICT;--> statement-breakpoint
ALTER TABLE "JournalEntryLines" ADD CONSTRAINT "FK_JournalEntryLines_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "TrustedDevices" ADD CONSTRAINT "FK_TrustedDevices_AspNetUsers" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "RecoveryCodes" ADD CONSTRAINT "FK_RecoveryCodes_AspNetUsers" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "SecuritySettings" ADD CONSTRAINT "FK_SecuritySettings_AspNetUsers" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "LoginActivities" ADD CONSTRAINT "FK_LoginActivities_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "UserSessions" ADD CONSTRAINT "FK_UserSessions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "hangfire"."state" ADD CONSTRAINT "state_jobid_fkey" FOREIGN KEY ("jobid") REFERENCES "hangfire"."job"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "hangfire"."jobparameter" ADD CONSTRAINT "jobparameter_jobid_fkey" FOREIGN KEY ("jobid") REFERENCES "hangfire"."job"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Notifications" ADD CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "GeneralLedgerPermanentAccounts" ADD CONSTRAINT "fk_pagl_account" FOREIGN KEY ("AccountId") REFERENCES "ChartOfAccounts"("Id") ON DELETE RESTRICT;--> statement-breakpoint
ALTER TABLE "GeneralLedgerPermanentAccounts" ADD CONSTRAINT "fk_pagl_journal_entry" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "GeneralLedgerPermanentAccounts" ADD CONSTRAINT "fk_pagl_journal_entry_line" FOREIGN KEY ("JournalEntryLineId") REFERENCES "JournalEntryLines"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "GeneralLedgerPermanentAccounts" ADD CONSTRAINT "fk_pagl_period" FOREIGN KEY ("PeriodId") REFERENCES "Periods"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "GeneralLedgerTemporaryAccounts" ADD CONSTRAINT "fk_tagl_account" FOREIGN KEY ("AccountId") REFERENCES "ChartOfAccounts"("Id") ON DELETE RESTRICT;--> statement-breakpoint
ALTER TABLE "GeneralLedgerTemporaryAccounts" ADD CONSTRAINT "fk_tagl_journal_entry" FOREIGN KEY ("JournalEntryId") REFERENCES "JournalEntries"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "GeneralLedgerTemporaryAccounts" ADD CONSTRAINT "fk_tagl_journal_entry_line" FOREIGN KEY ("JournalEntryLineId") REFERENCES "JournalEntryLines"("Id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "GeneralLedgerTemporaryAccounts" ADD CONSTRAINT "fk_tagl_period" FOREIGN KEY ("PeriodId") REFERENCES "Periods"("Id") ON DELETE CASCADE;
*/