-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE SCHEMA "hangfire";
--> statement-breakpoint
CREATE TABLE "__EFMigrationsHistory" (
	"MigrationId" varchar(150) PRIMARY KEY NOT NULL,
	"ProductVersion" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "AspNetRoles" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"Name" varchar(256),
	"NormalizedName" varchar(256),
	"ConcurrencyStamp" text
);
--> statement-breakpoint
CREATE TABLE "AspNetRoleClaims" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""AspNetRoleClaims_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"RoleId" uuid NOT NULL,
	"ClaimType" text,
	"ClaimValue" text
);
--> statement-breakpoint
CREATE TABLE "AspNetUserClaims" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""AspNetUserClaims_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"UserId" uuid NOT NULL,
	"ClaimType" text,
	"ClaimValue" text
);
--> statement-breakpoint
CREATE TABLE "AspNetUsers" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"FullName" text,
	"UserName" varchar(256),
	"NormalizedUserName" varchar(256),
	"Email" varchar(256),
	"NormalizedEmail" varchar(256),
	"EmailConfirmed" boolean NOT NULL,
	"PasswordHash" text,
	"SecurityStamp" text,
	"ConcurrencyStamp" text,
	"PhoneNumber" text,
	"PhoneNumberConfirmed" boolean NOT NULL,
	"TwoFactorEnabled" boolean NOT NULL,
	"LockoutEnd" timestamp with time zone,
	"LockoutEnabled" boolean NOT NULL,
	"AccessFailedCount" integer NOT NULL,
	"AvatarUrl" text,
	"Bio" text
);
--> statement-breakpoint
CREATE TABLE "ChartOfAccounts" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""ChartOfAccounts_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"ReferenceNumber" integer NOT NULL,
	"AccountName" varchar(100) NOT NULL,
	"Type" text NOT NULL,
	"Role" text NOT NULL,
	"IsActive" boolean NOT NULL,
	"UserId" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "JournalEntries" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""JournalEntries_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"JournalType" varchar(50) NOT NULL,
	"EntryDate" timestamp with time zone NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"TransactionNumber" varchar(30) NOT NULL,
	"UserId" uuid NOT NULL,
	"UpdatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "Notifications" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"Title" text NOT NULL,
	"Message" text NOT NULL,
	"Type" text NOT NULL,
	"IsRead" boolean NOT NULL,
	"TargetUrl" text,
	"CreatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "EconomicDocuments" (
	"Id" serial PRIMARY KEY NOT NULL,
	"Title" varchar(200) NOT NULL,
	"Category" varchar(50) NOT NULL,
	"ReferenceNumber" varchar(100),
	"FileName" varchar(255) NOT NULL,
	"FilePath" varchar(500) NOT NULL,
	"FileSize" bigint NOT NULL,
	"ContentType" varchar(100),
	"UploadedBy" text NOT NULL,
	"UploadDate" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"Description" text,
	"JournalEntryId" bigint,
	"UserId" uuid NOT NULL,
	"CloudPublicId" varchar(150),
	"FolderId" uuid
);
--> statement-breakpoint
CREATE TABLE "JournalEntryLines" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""JournalEntryLines_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"JournalEntryId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"LineDescription" varchar(250),
	"Debit" numeric(18, 2) NOT NULL,
	"Credit" numeric(18, 2) NOT NULL,
	"LineOrder" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "DataProtectionKeys" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""DataProtectionKeys_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"FriendlyName" text,
	"Xml" text
);
--> statement-breakpoint
CREATE TABLE "RecoveryCodes" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"CodeHash" varchar(255) NOT NULL,
	"Used" boolean DEFAULT false NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL,
	"UsedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "SecuritySettings" (
	"UserId" uuid PRIMARY KEY NOT NULL,
	"EmailVerified" boolean DEFAULT false NOT NULL,
	"TwoFactorEnabled" boolean DEFAULT false NOT NULL,
	"LoginNotificationEnabled" boolean DEFAULT true NOT NULL,
	"SessionTimeoutMinutes" integer DEFAULT 30 NOT NULL,
	"UpdatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "UserSessions" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"DeviceName" text NOT NULL,
	"Browser" text NOT NULL,
	"OperatingSystem" text NOT NULL,
	"IpAddress" text NOT NULL,
	"Country" text NOT NULL,
	"UserAgent" text NOT NULL,
	"RefreshTokenHash" text NOT NULL,
	"IsActive" boolean NOT NULL,
	"IsCurrent" boolean NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL,
	"LastActivityAt" timestamp with time zone NOT NULL,
	"RevokedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "LoginActivities" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"ActivityType" text NOT NULL,
	"IsSuccess" boolean NOT NULL,
	"Device" text NOT NULL,
	"Browser" text NOT NULL,
	"OperatingSystem" text NOT NULL,
	"IpAddress" text NOT NULL,
	"Country" text NOT NULL,
	"UserAgent" text NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "TrustedDevices" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"DeviceName" varchar(100) NOT NULL,
	"DeviceIdentifier" varchar(255) NOT NULL,
	"Browser" varchar(100) NOT NULL,
	"OperatingSystem" varchar(100) NOT NULL,
	"IsTrusted" boolean DEFAULT true NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL,
	"LastUsedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "TrustedDevices_DeviceIdentifier_key" UNIQUE("DeviceIdentifier")
);
--> statement-breakpoint
CREATE TABLE "Periods" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Periods_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"PeriodName" varchar(50) NOT NULL,
	"StartDate" timestamp with time zone NOT NULL,
	"EndDate" timestamp with time zone NOT NULL,
	"IsClosed" boolean DEFAULT false NOT NULL,
	"IsSelected" boolean DEFAULT false NOT NULL,
	"UserId" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Folders" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"Name" varchar(150) NOT NULL,
	"ParentFolderId" uuid,
	"UserId" uuid NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "TransactionCounters" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""TransactionCounters_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"UserId" uuid NOT NULL,
	"CounterKey" varchar(10) NOT NULL,
	"LastSequence" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."schema" (
	"version" integer PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."counter" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"key" text NOT NULL,
	"value" bigint NOT NULL,
	"expireat" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hangfire"."hash" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"key" text NOT NULL,
	"field" text NOT NULL,
	"value" text,
	"expireat" timestamp with time zone,
	"updatecount" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "hash_key_field_key" UNIQUE("key","field")
);
--> statement-breakpoint
CREATE TABLE "hangfire"."job" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"stateid" bigint,
	"statename" text,
	"invocationdata" jsonb NOT NULL,
	"arguments" jsonb NOT NULL,
	"createdat" timestamp with time zone NOT NULL,
	"expireat" timestamp with time zone,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."server" (
	"id" text PRIMARY KEY NOT NULL,
	"data" jsonb,
	"lastheartbeat" timestamp with time zone NOT NULL,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."lock" (
	"resource" text NOT NULL,
	"updatecount" integer DEFAULT 0 NOT NULL,
	"acquired" timestamp with time zone,
	CONSTRAINT "lock_resource_key" UNIQUE("resource")
);
--> statement-breakpoint
CREATE TABLE "hangfire"."state" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"jobid" bigint NOT NULL,
	"name" text NOT NULL,
	"reason" text,
	"createdat" timestamp with time zone NOT NULL,
	"data" jsonb,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."jobqueue" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"jobid" bigint NOT NULL,
	"queue" text NOT NULL,
	"fetchedat" timestamp with time zone,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."jobparameter" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"jobid" bigint NOT NULL,
	"name" text NOT NULL,
	"value" text,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."aggregatedcounter" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"key" text NOT NULL,
	"value" bigint NOT NULL,
	"expireat" timestamp with time zone,
	CONSTRAINT "aggregatedcounter_key_key" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "hangfire"."list" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"key" text NOT NULL,
	"value" text,
	"expireat" timestamp with time zone,
	"updatecount" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hangfire"."set" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"key" text NOT NULL,
	"score" double precision NOT NULL,
	"value" text NOT NULL,
	"expireat" timestamp with time zone,
	"updatecount" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "set_key_value_key" UNIQUE("value","key")
);
--> statement-breakpoint
CREATE TABLE "AspNetUserRoles" (
	"UserId" uuid NOT NULL,
	"RoleId" uuid NOT NULL,
	CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY("UserId","RoleId")
);
--> statement-breakpoint
CREATE TABLE "AspNetUserLogins" (
	"LoginProvider" text NOT NULL,
	"ProviderKey" text NOT NULL,
	"ProviderDisplayName" text,
	"UserId" uuid NOT NULL,
	CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY("ProviderKey","LoginProvider")
);
--> statement-breakpoint
CREATE TABLE "AspNetUserTokens" (
	"UserId" uuid NOT NULL,
	"LoginProvider" text NOT NULL,
	"Name" text NOT NULL,
	"Value" text,
	CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY("UserId","Name","LoginProvider")
);
--> statement-breakpoint
ALTER TABLE "AspNetRoleClaims" ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "public"."AspNetRoles"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "JournalEntries" ADD CONSTRAINT "FK_JournalEntries_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Notifications" ADD CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "EconomicDocuments" ADD CONSTRAINT "FK_EconomicDocuments_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "public"."JournalEntries"("Id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "EconomicDocuments" ADD CONSTRAINT "EconomicDocuments_FolderId_fkey" FOREIGN KEY ("FolderId") REFERENCES "public"."Folders"("Id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "JournalEntryLines" ADD CONSTRAINT "FK_JournalEntryLines_ChartOfAccounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "public"."ChartOfAccounts"("Id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "JournalEntryLines" ADD CONSTRAINT "FK_JournalEntryLines_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "public"."JournalEntries"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "RecoveryCodes" ADD CONSTRAINT "FK_RecoveryCodes_AspNetUsers" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "SecuritySettings" ADD CONSTRAINT "FK_SecuritySettings_AspNetUsers" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "UserSessions" ADD CONSTRAINT "FK_UserSessions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "LoginActivities" ADD CONSTRAINT "FK_LoginActivities_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TrustedDevices" ADD CONSTRAINT "FK_TrustedDevices_AspNetUsers" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Folders" ADD CONSTRAINT "Folders_ParentFolderId_fkey" FOREIGN KEY ("ParentFolderId") REFERENCES "public"."Folders"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hangfire"."state" ADD CONSTRAINT "state_jobid_fkey" FOREIGN KEY ("jobid") REFERENCES "hangfire"."job"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "hangfire"."jobparameter" ADD CONSTRAINT "jobparameter_jobid_fkey" FOREIGN KEY ("jobid") REFERENCES "hangfire"."job"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "public"."AspNetRoles"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "public"."AspNetUsers"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" USING btree ("NormalizedName" text_ops);--> statement-breakpoint
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" USING btree ("RoleId" uuid_ops);--> statement-breakpoint
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE INDEX "EmailIndex" ON "AspNetUsers" USING btree ("NormalizedEmail" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" USING btree ("NormalizedUserName" text_ops);--> statement-breakpoint
CREATE INDEX "IX_ChartOfAccounts_UserId" ON "ChartOfAccounts" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "IX_ChartOfAccounts_UserId_ReferenceNumber" ON "ChartOfAccounts" USING btree ("UserId" int4_ops,"ReferenceNumber" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_JournalEntries_UserId" ON "JournalEntries" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "IX_JournalEntries_UserId_TransactionNumber" ON "JournalEntries" USING btree ("UserId" text_ops,"TransactionNumber" text_ops);--> statement-breakpoint
CREATE INDEX "IX_Notifications_UserId_IsRead_CreatedAt" ON "Notifications" USING btree ("UserId" timestamptz_ops,"IsRead" uuid_ops,"CreatedAt" uuid_ops);--> statement-breakpoint
CREATE INDEX "IX_EconomicDocuments_Category" ON "EconomicDocuments" USING btree ("Category" text_ops);--> statement-breakpoint
CREATE INDEX "IX_EconomicDocuments_FolderId" ON "EconomicDocuments" USING btree ("FolderId" uuid_ops);--> statement-breakpoint
CREATE INDEX "IX_EconomicDocuments_JournalEntryId" ON "EconomicDocuments" USING btree ("JournalEntryId" int8_ops);--> statement-breakpoint
CREATE INDEX "IX_EconomicDocuments_ReferenceNumber" ON "EconomicDocuments" USING btree ("ReferenceNumber" text_ops);--> statement-breakpoint
CREATE INDEX "IX_EconomicDocuments_UserId" ON "EconomicDocuments" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE INDEX "IX_JournalEntryLines_AccountId" ON "JournalEntryLines" USING btree ("AccountId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_JournalEntryLines_JournalEntryId" ON "JournalEntryLines" USING btree ("JournalEntryId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_RecoveryCodes_UserId" ON "RecoveryCodes" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE INDEX "IX_UserSessions_UserId_IsActive" ON "UserSessions" USING btree ("UserId" bool_ops,"IsActive" bool_ops);--> statement-breakpoint
CREATE INDEX "IX_LoginActivities_UserId_CreatedAt" ON "LoginActivities" USING btree ("UserId" timestamptz_ops,"CreatedAt" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "IX_TrustedDevices_UserId" ON "TrustedDevices" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "IX_Periods_IsSelected_Unique" ON "Periods" USING btree ("UserId" uuid_ops) WHERE ("IsSelected" = true);--> statement-breakpoint
CREATE INDEX "IX_Periods_UserId" ON "Periods" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE INDEX "IX_Folders_ParentFolderId" ON "Folders" USING btree ("ParentFolderId" uuid_ops);--> statement-breakpoint
CREATE INDEX "IX_Folders_UserId" ON "Folders" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "IX_TransactionCounters_UserId_CounterKey" ON "TransactionCounters" USING btree ("UserId" text_ops,"CounterKey" text_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_counter_expireat" ON "hangfire"."counter" USING btree ("expireat" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_counter_key" ON "hangfire"."counter" USING btree ("key" text_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_hash_expireat" ON "hangfire"."hash" USING btree ("expireat" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_job_expireat" ON "hangfire"."job" USING btree ("expireat" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_job_statename" ON "hangfire"."job" USING btree ("statename" text_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_job_statename_is_not_null" ON "hangfire"."job" USING btree ("statename" text_ops,"id" text_ops) WHERE (statename IS NOT NULL);--> statement-breakpoint
CREATE INDEX "ix_hangfire_state_jobid" ON "hangfire"."state" USING btree ("jobid" int8_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_jobqueue_fetchedat_queue_jobid" ON "hangfire"."jobqueue" USING btree ("fetchedat" timestamptz_ops,"queue" text_ops,"jobid" text_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_jobqueue_jobidandqueue" ON "hangfire"."jobqueue" USING btree ("jobid" text_ops,"queue" int8_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_jobqueue_queueandfetchedat" ON "hangfire"."jobqueue" USING btree ("queue" text_ops,"fetchedat" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_jobparameter_jobidandname" ON "hangfire"."jobparameter" USING btree ("jobid" int8_ops,"name" int8_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_list_expireat" ON "hangfire"."list" USING btree ("expireat" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_set_expireat" ON "hangfire"."set" USING btree ("expireat" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "ix_hangfire_set_key_score" ON "hangfire"."set" USING btree ("key" float8_ops,"score" float8_ops);--> statement-breakpoint
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" USING btree ("RoleId" uuid_ops);--> statement-breakpoint
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" USING btree ("UserId" uuid_ops);
*/