-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "Worksheet" (
	"Id" serial PRIMARY KEY NOT NULL,
	"PeriodDate" date,
	"AccountNumber" varchar(50) NOT NULL,
	"AccountName" varchar(255) NOT NULL,
	"TrialBalanceDebit" numeric(18, 2) DEFAULT '0',
	"TrialBalanceCredit" numeric(18, 2) DEFAULT '0',
	"AdjustingJournalDebit" numeric(18, 2) DEFAULT '0',
	"AdjustingJournalCredit" numeric(18, 2) DEFAULT '0',
	"TrialBalanceAdjustedDebit" numeric(18, 2) DEFAULT '0',
	"TrialBalanceAdjustedCredit" numeric(18, 2) DEFAULT '0',
	"IncomeStatementDebit" numeric(18, 2) DEFAULT '0',
	"IncomeStatementCredit" numeric(18, 2) DEFAULT '0',
	"FinancialPositionDebit" numeric(18, 2) DEFAULT '0',
	"FinancialPositionCredit" numeric(18, 2) DEFAULT '0',
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "__EFMigrationsHistory" (
	"MigrationId" varchar(150) PRIMARY KEY NOT NULL,
	"ProductVersion" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ChartOfAccounts" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""ChartOfAccounts_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"ReferenceNumber" integer NOT NULL,
	"AccountName" varchar(100) NOT NULL,
	"Type" text NOT NULL,
	"Role" text NOT NULL,
	"IsActive" boolean NOT NULL,
	"UserId" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "JournalEntries" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""JournalEntries_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"JournalType" varchar(50) NOT NULL,
	"EntryDate" timestamp with time zone NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"TransactionNumber" varchar(30) NOT NULL,
	"UserId" uuid NOT NULL,
	"UpdatedAt" timestamp with time zone,
	"Description" text,
	"Status" text DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE "Notifications" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"Title" text NOT NULL,
	"Message" text NOT NULL,
	"Type" text NOT NULL,
	"IsRead" boolean NOT NULL,
	"TargetUrl" text,
	"CreatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "JournalEntryLines" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""JournalEntryLines_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"JournalEntryId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"LineDescription" varchar(250),
	"Debit" numeric(18, 2) NOT NULL,
	"Credit" numeric(18, 2) NOT NULL,
	"LineOrder" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "DataProtectionKeys" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""DataProtectionKeys_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"FriendlyName" text,
	"Xml" text
);
--> statement-breakpoint
CREATE TABLE "RecoveryCodes" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"CodeHash" varchar(255) NOT NULL,
	"Used" boolean DEFAULT false NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL,
	"UsedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "SecuritySettings" (
	"UserId" uuid PRIMARY KEY NOT NULL,
	"EmailVerified" boolean DEFAULT false NOT NULL,
	"TwoFactorEnabled" boolean DEFAULT false NOT NULL,
	"LoginNotificationEnabled" boolean DEFAULT true NOT NULL,
	"SessionTimeoutMinutes" integer DEFAULT 30 NOT NULL,
	"UpdatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "UserSessions" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"DeviceName" text NOT NULL,
	"Browser" text NOT NULL,
	"OperatingSystem" text NOT NULL,
	"IpAddress" text NOT NULL,
	"Country" text NOT NULL,
	"UserAgent" text NOT NULL,
	"RefreshTokenHash" text NOT NULL,
	"IsActive" boolean NOT NULL,
	"IsCurrent" boolean NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL,
	"LastActivityAt" timestamp with time zone NOT NULL,
	"RevokedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "LoginActivities" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"ActivityType" text NOT NULL,
	"IsSuccess" boolean NOT NULL,
	"Device" text NOT NULL,
	"Browser" text NOT NULL,
	"OperatingSystem" text NOT NULL,
	"IpAddress" text NOT NULL,
	"Country" text NOT NULL,
	"UserAgent" text NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "TrustedDevices" (
	"Id" uuid PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"DeviceName" varchar(100) NOT NULL,
	"DeviceIdentifier" varchar(255) NOT NULL,
	"Browser" varchar(100) NOT NULL,
	"OperatingSystem" varchar(100) NOT NULL,
	"IsTrusted" boolean DEFAULT true NOT NULL,
	"CreatedAt" timestamp with time zone NOT NULL,
	"LastUsedAt" timestamp with time zone NOT NULL,
	CONSTRAINT "TrustedDevices_DeviceIdentifier_key" UNIQUE("DeviceIdentifier")
);
--> statement-breakpoint
CREATE TABLE "GeneralLedgerPermanentAccounts" (
	"Id" serial PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"PeriodId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"JournalEntryId" integer NOT NULL,
	"JournalEntryLineId" integer NOT NULL,
	"EntryDate" timestamp with time zone NOT NULL,
	"TransactionNumber" varchar(255) NOT NULL,
	"LineDescription" text,
	"Debit" numeric(18, 2) DEFAULT '0.00' NOT NULL,
	"Credit" numeric(18, 2) DEFAULT '0.00' NOT NULL,
	"RunningBalance" numeric(18, 2) DEFAULT '0.00' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Periods" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Periods_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"PeriodName" varchar(50) NOT NULL,
	"StartDate" timestamp with time zone NOT NULL,
	"EndDate" timestamp with time zone NOT NULL,
	"IsClosed" boolean DEFAULT false NOT NULL,
	"IsSelected" boolean DEFAULT false NOT NULL,
	"UserId" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "GeneralLedgerTemporaryAccounts" (
	"Id" serial PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"PeriodId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"JournalEntryId" integer NOT NULL,
	"JournalEntryLineId" integer NOT NULL,
	"EntryDate" timestamp with time zone NOT NULL,
	"TransactionNumber" varchar(255) NOT NULL,
	"LineDescription" text,
	"Debit" numeric(18, 2) DEFAULT '0.00' NOT NULL,
	"Credit" numeric(18, 2) DEFAULT '0.00' NOT NULL,
	"RunningBalance" numeric(18, 2) DEFAULT '0.00' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "TransactionCounters" (
	"Id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""TransactionCounters_Id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"UserId" uuid NOT NULL,
	"CounterKey" varchar(10) NOT NULL,
	"LastSequence" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "GeneralJournal" (
	"Id" serial PRIMARY KEY NOT NULL,
	"JournalEntryId" integer,
	"TransactionNumber" varchar(255),
	"EntryDate" timestamp with time zone,
	"JournalType" varchar(255),
	"HeaderDescription" text,
	"Status" text,
	"UserId" uuid,
	"LineId" integer,
	"AccountId" integer,
	"LineDescription" varchar(255),
	"Debit" numeric,
	"Credit" numeric,
	"LineOrder" integer,
	"CreatedAt" timestamp with time zone,
	"UpdatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "AdjustingJournal" (
	"Id" serial PRIMARY KEY NOT NULL,
	"JournalEntryId" integer,
	"TransactionNumber" varchar,
	"EntryDate" timestamp with time zone,
	"JournalType" varchar,
	"HeaderDescription" text,
	"Status" text,
	"UserId" uuid,
	"LineId" integer,
	"AccountId" integer,
	"LineDescription" varchar,
	"Debit" numeric,
	"Credit" numeric,
	"LineOrder" integer,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "ClosingJournal" (
	"Id" serial PRIMARY KEY NOT NULL,
	"JournalEntryId" integer,
	"TransactionNumber" varchar,
	"EntryDate" timestamp with time zone,
	"JournalType" varchar,
	"HeaderDescription" text,
	"Status" text,
	"UserId" uuid,
	"LineId" integer,
	"AccountId" integer,
	"LineDescription" varchar,
	"Debit" numeric,
	"Credit" numeric,
	"LineOrder" integer,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "TrialBalanceAdjusted" (
	"Id" serial PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"PeriodId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"EndingDebit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"EndingCredit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "UQ_TB_Adjusted_User_Period_Account" UNIQUE("UserId","PeriodId","AccountId")
);
--> statement-breakpoint
CREATE TABLE "TrialBalancePostClosing" (
	"Id" serial PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"PeriodId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"EndingDebit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"EndingCredit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "UQ_TB_PostClosing_User_Period_Account" UNIQUE("UserId","PeriodId","AccountId")
);
--> statement-breakpoint
CREATE TABLE "TrialBalance" (
	"Id" serial PRIMARY KEY NOT NULL,
	"UserId" uuid NOT NULL,
	"PeriodId" integer NOT NULL,
	"AccountId" integer NOT NULL,
	"EndingDebit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"EndingCredit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"UpdatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "UQ_TB_Unadjusted_User_Period_Account" UNIQUE("UserId","PeriodId","AccountId")
);
--> statement-breakpoint
ALTER TABLE "JournalEntryLines" ADD CONSTRAINT "FK_JournalEntryLines_ChartOfAccounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "public"."ChartOfAccounts"("Id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "JournalEntryLines" ADD CONSTRAINT "FK_JournalEntryLines_JournalEntries_JournalEntryId" FOREIGN KEY ("JournalEntryId") REFERENCES "public"."JournalEntries"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GeneralLedgerPermanentAccounts" ADD CONSTRAINT "fk_pagl_period" FOREIGN KEY ("PeriodId") REFERENCES "public"."Periods"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GeneralLedgerPermanentAccounts" ADD CONSTRAINT "fk_pagl_account" FOREIGN KEY ("AccountId") REFERENCES "public"."ChartOfAccounts"("Id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GeneralLedgerPermanentAccounts" ADD CONSTRAINT "fk_pagl_journal_entry" FOREIGN KEY ("JournalEntryId") REFERENCES "public"."JournalEntries"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GeneralLedgerPermanentAccounts" ADD CONSTRAINT "fk_pagl_journal_entry_line" FOREIGN KEY ("JournalEntryLineId") REFERENCES "public"."JournalEntryLines"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GeneralLedgerTemporaryAccounts" ADD CONSTRAINT "fk_tagl_journal_entry_line" FOREIGN KEY ("JournalEntryLineId") REFERENCES "public"."JournalEntryLines"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GeneralLedgerTemporaryAccounts" ADD CONSTRAINT "fk_tagl_period" FOREIGN KEY ("PeriodId") REFERENCES "public"."Periods"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GeneralLedgerTemporaryAccounts" ADD CONSTRAINT "fk_tagl_account" FOREIGN KEY ("AccountId") REFERENCES "public"."ChartOfAccounts"("Id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "GeneralLedgerTemporaryAccounts" ADD CONSTRAINT "fk_tagl_journal_entry" FOREIGN KEY ("JournalEntryId") REFERENCES "public"."JournalEntries"("Id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IX_ChartOfAccounts_UserId" ON "ChartOfAccounts" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "IX_ChartOfAccounts_UserId_ReferenceNumber" ON "ChartOfAccounts" USING btree ("UserId" int4_ops,"ReferenceNumber" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_JournalEntries_UserId" ON "JournalEntries" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "IX_JournalEntries_UserId_TransactionNumber" ON "JournalEntries" USING btree ("UserId" text_ops,"TransactionNumber" text_ops);--> statement-breakpoint
CREATE INDEX "IX_Notifications_UserId_IsRead_CreatedAt" ON "Notifications" USING btree ("UserId" timestamptz_ops,"IsRead" uuid_ops,"CreatedAt" uuid_ops);--> statement-breakpoint
CREATE INDEX "IX_JournalEntryLines_AccountId" ON "JournalEntryLines" USING btree ("AccountId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_JournalEntryLines_JournalEntryId" ON "JournalEntryLines" USING btree ("JournalEntryId" int4_ops);--> statement-breakpoint
CREATE INDEX "IX_RecoveryCodes_UserId" ON "RecoveryCodes" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE INDEX "IX_UserSessions_UserId_IsActive" ON "UserSessions" USING btree ("UserId" bool_ops,"IsActive" bool_ops);--> statement-breakpoint
CREATE INDEX "IX_LoginActivities_UserId_CreatedAt" ON "LoginActivities" USING btree ("UserId" timestamptz_ops,"CreatedAt" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "IX_TrustedDevices_UserId" ON "TrustedDevices" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_pagl_user_period_account" ON "GeneralLedgerPermanentAccounts" USING btree ("UserId" int4_ops,"PeriodId" int4_ops,"AccountId" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "IX_Periods_IsSelected_Unique" ON "Periods" USING btree ("UserId" uuid_ops) WHERE ("IsSelected" = true);--> statement-breakpoint
CREATE INDEX "IX_Periods_UserId" ON "Periods" USING btree ("UserId" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_tagl_user_period_account" ON "GeneralLedgerTemporaryAccounts" USING btree ("UserId" uuid_ops,"PeriodId" int4_ops,"AccountId" uuid_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "IX_TransactionCounters_UserId_CounterKey" ON "TransactionCounters" USING btree ("UserId" text_ops,"CounterKey" text_ops);
*/