/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAiassistantRouteImport } from './routes/_authenticated/aiassistant'
import { Route as AuthenticatedChartOfAccountsRouteImport } from './routes/_authenticated/chart-of-accounts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGuardianRouteImport } from './routes/_authenticated/guardian'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedJournalEntryRouteImport } from './routes/_authenticated/journal-entry'
import { Route as AuthenticatedPeriodsRouteImport } from './routes/_authenticated/periods'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedReportsAdjustedTrialBalanceRouteImport } from './routes/_authenticated/reports/adjusted-trial-balance'
import { Route as AuthenticatedReportsAdjustingJournalRouteImport } from './routes/_authenticated/reports/adjusting-journal'
import { Route as AuthenticatedReportsClosingJournalRouteImport } from './routes/_authenticated/reports/closing-journal'
import { Route as AuthenticatedReportsGeneralJournalRouteImport } from './routes/_authenticated/reports/general-journal'
import { Route as AuthenticatedReportsGeneralLedgerPermanentRouteImport } from './routes/_authenticated/reports/general-ledger-permanent'
import { Route as AuthenticatedReportsGeneralLedgerTemporaryRouteImport } from './routes/_authenticated/reports/general-ledger-temporary'
import { Route as AuthenticatedReportsIncomeStatementRouteImport } from './routes/_authenticated/reports/income-statement'
import { Route as AuthenticatedReportsPostClosingTrialBalanceRouteImport } from './routes/_authenticated/reports/post-closing-trial-balance'
import { Route as AuthenticatedReportsRetainedEarningsRouteImport } from './routes/_authenticated/reports/retained-earnings'
import { Route as AuthenticatedReportsStatementOfCashFlowRouteImport } from './routes/_authenticated/reports/statement-of-cash-flow'
import { Route as AuthenticatedReportsStatementOfFinancialPositionRouteImport } from './routes/_authenticated/reports/statement-of-financial-position'
import { Route as AuthenticatedReportsUnadjustedTrialBalanceRouteImport } from './routes/_authenticated/reports/unadjusted-trial-balance'
import { Route as AuthenticatedReportsWorksheetRouteImport } from './routes/_authenticated/reports/worksheet'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiassistantRoute =
  AuthenticatedAiassistantRouteImport.update({
    id: '/aiassistant',
    path: '/aiassistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChartOfAccountsRoute =
  AuthenticatedChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuardianRoute = AuthenticatedGuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalEntryRoute =
  AuthenticatedJournalEntryRouteImport.update({
    id: '/journal-entry',
    path: '/journal-entry',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPeriodsRoute = AuthenticatedPeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsAdjustedTrialBalanceRoute =
  AuthenticatedReportsAdjustedTrialBalanceRouteImport.update({
    id: '/reports/adjusted-trial-balance',
    path: '/reports/adjusted-trial-balance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsAdjustingJournalRoute =
  AuthenticatedReportsAdjustingJournalRouteImport.update({
    id: '/reports/adjusting-journal',
    path: '/reports/adjusting-journal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsClosingJournalRoute =
  AuthenticatedReportsClosingJournalRouteImport.update({
    id: '/reports/closing-journal',
    path: '/reports/closing-journal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsGeneralJournalRoute =
  AuthenticatedReportsGeneralJournalRouteImport.update({
    id: '/reports/general-journal',
    path: '/reports/general-journal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsGeneralLedgerPermanentRoute =
  AuthenticatedReportsGeneralLedgerPermanentRouteImport.update({
    id: '/reports/general-ledger-permanent',
    path: '/reports/general-ledger-permanent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsGeneralLedgerTemporaryRoute =
  AuthenticatedReportsGeneralLedgerTemporaryRouteImport.update({
    id: '/reports/general-ledger-temporary',
    path: '/reports/general-ledger-temporary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIncomeStatementRoute =
  AuthenticatedReportsIncomeStatementRouteImport.update({
    id: '/reports/income-statement',
    path: '/reports/income-statement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsPostClosingTrialBalanceRoute =
  AuthenticatedReportsPostClosingTrialBalanceRouteImport.update({
    id: '/reports/post-closing-trial-balance',
    path: '/reports/post-closing-trial-balance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRetainedEarningsRoute =
  AuthenticatedReportsRetainedEarningsRouteImport.update({
    id: '/reports/retained-earnings',
    path: '/reports/retained-earnings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsStatementOfCashFlowRoute =
  AuthenticatedReportsStatementOfCashFlowRouteImport.update({
    id: '/reports/statement-of-cash-flow',
    path: '/reports/statement-of-cash-flow',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsStatementOfFinancialPositionRoute =
  AuthenticatedReportsStatementOfFinancialPositionRouteImport.update({
    id: '/reports/statement-of-financial-position',
    path: '/reports/statement-of-financial-position',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsUnadjustedTrialBalanceRoute =
  AuthenticatedReportsUnadjustedTrialBalanceRouteImport.update({
    id: '/reports/unadjusted-trial-balance',
    path: '/reports/unadjusted-trial-balance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsWorksheetRoute =
  AuthenticatedReportsWorksheetRouteImport.update({
    id: '/reports/worksheet',
    path: '/reports/worksheet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/aiassistant': typeof AuthenticatedAiassistantRoute
  '/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guardian': typeof AuthenticatedGuardianRoute
  '/home': typeof AuthenticatedHomeRoute
  '/journal-entry': typeof AuthenticatedJournalEntryRoute
  '/periods': typeof AuthenticatedPeriodsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/reports/adjusted-trial-balance': typeof AuthenticatedReportsAdjustedTrialBalanceRoute
  '/reports/adjusting-journal': typeof AuthenticatedReportsAdjustingJournalRoute
  '/reports/closing-journal': typeof AuthenticatedReportsClosingJournalRoute
  '/reports/general-journal': typeof AuthenticatedReportsGeneralJournalRoute
  '/reports/general-ledger-permanent': typeof AuthenticatedReportsGeneralLedgerPermanentRoute
  '/reports/general-ledger-temporary': typeof AuthenticatedReportsGeneralLedgerTemporaryRoute
  '/reports/income-statement': typeof AuthenticatedReportsIncomeStatementRoute
  '/reports/post-closing-trial-balance': typeof AuthenticatedReportsPostClosingTrialBalanceRoute
  '/reports/retained-earnings': typeof AuthenticatedReportsRetainedEarningsRoute
  '/reports/statement-of-cash-flow': typeof AuthenticatedReportsStatementOfCashFlowRoute
  '/reports/statement-of-financial-position': typeof AuthenticatedReportsStatementOfFinancialPositionRoute
  '/reports/unadjusted-trial-balance': typeof AuthenticatedReportsUnadjustedTrialBalanceRoute
  '/reports/worksheet': typeof AuthenticatedReportsWorksheetRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/aiassistant': typeof AuthenticatedAiassistantRoute
  '/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guardian': typeof AuthenticatedGuardianRoute
  '/home': typeof AuthenticatedHomeRoute
  '/journal-entry': typeof AuthenticatedJournalEntryRoute
  '/periods': typeof AuthenticatedPeriodsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/': typeof AuthenticatedIndexRoute
  '/reports/adjusted-trial-balance': typeof AuthenticatedReportsAdjustedTrialBalanceRoute
  '/reports/adjusting-journal': typeof AuthenticatedReportsAdjustingJournalRoute
  '/reports/closing-journal': typeof AuthenticatedReportsClosingJournalRoute
  '/reports/general-journal': typeof AuthenticatedReportsGeneralJournalRoute
  '/reports/general-ledger-permanent': typeof AuthenticatedReportsGeneralLedgerPermanentRoute
  '/reports/general-ledger-temporary': typeof AuthenticatedReportsGeneralLedgerTemporaryRoute
  '/reports/income-statement': typeof AuthenticatedReportsIncomeStatementRoute
  '/reports/post-closing-trial-balance': typeof AuthenticatedReportsPostClosingTrialBalanceRoute
  '/reports/retained-earnings': typeof AuthenticatedReportsRetainedEarningsRoute
  '/reports/statement-of-cash-flow': typeof AuthenticatedReportsStatementOfCashFlowRoute
  '/reports/statement-of-financial-position': typeof AuthenticatedReportsStatementOfFinancialPositionRoute
  '/reports/unadjusted-trial-balance': typeof AuthenticatedReportsUnadjustedTrialBalanceRoute
  '/reports/worksheet': typeof AuthenticatedReportsWorksheetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aiassistant': typeof AuthenticatedAiassistantRoute
  '/_authenticated/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/guardian': typeof AuthenticatedGuardianRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/journal-entry': typeof AuthenticatedJournalEntryRoute
  '/_authenticated/periods': typeof AuthenticatedPeriodsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/reports/adjusted-trial-balance': typeof AuthenticatedReportsAdjustedTrialBalanceRoute
  '/_authenticated/reports/adjusting-journal': typeof AuthenticatedReportsAdjustingJournalRoute
  '/_authenticated/reports/closing-journal': typeof AuthenticatedReportsClosingJournalRoute
  '/_authenticated/reports/general-journal': typeof AuthenticatedReportsGeneralJournalRoute
  '/_authenticated/reports/general-ledger-permanent': typeof AuthenticatedReportsGeneralLedgerPermanentRoute
  '/_authenticated/reports/general-ledger-temporary': typeof AuthenticatedReportsGeneralLedgerTemporaryRoute
  '/_authenticated/reports/income-statement': typeof AuthenticatedReportsIncomeStatementRoute
  '/_authenticated/reports/post-closing-trial-balance': typeof AuthenticatedReportsPostClosingTrialBalanceRoute
  '/_authenticated/reports/retained-earnings': typeof AuthenticatedReportsRetainedEarningsRoute
  '/_authenticated/reports/statement-of-cash-flow': typeof AuthenticatedReportsStatementOfCashFlowRoute
  '/_authenticated/reports/statement-of-financial-position': typeof AuthenticatedReportsStatementOfFinancialPositionRoute
  '/_authenticated/reports/unadjusted-trial-balance': typeof AuthenticatedReportsUnadjustedTrialBalanceRoute
  '/_authenticated/reports/worksheet': typeof AuthenticatedReportsWorksheetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aiassistant'
    | '/chart-of-accounts'
    | '/dashboard'
    | '/guardian'
    | '/home'
    | '/journal-entry'
    | '/periods'
    | '/settings'
    | '/tools'
    | '/reports/adjusted-trial-balance'
    | '/reports/adjusting-journal'
    | '/reports/closing-journal'
    | '/reports/general-journal'
    | '/reports/general-ledger-permanent'
    | '/reports/general-ledger-temporary'
    | '/reports/income-statement'
    | '/reports/post-closing-trial-balance'
    | '/reports/retained-earnings'
    | '/reports/statement-of-cash-flow'
    | '/reports/statement-of-financial-position'
    | '/reports/unadjusted-trial-balance'
    | '/reports/worksheet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/aiassistant'
    | '/chart-of-accounts'
    | '/dashboard'
    | '/guardian'
    | '/home'
    | '/journal-entry'
    | '/periods'
    | '/settings'
    | '/tools'
    | '/'
    | '/reports/adjusted-trial-balance'
    | '/reports/adjusting-journal'
    | '/reports/closing-journal'
    | '/reports/general-journal'
    | '/reports/general-ledger-permanent'
    | '/reports/general-ledger-temporary'
    | '/reports/income-statement'
    | '/reports/post-closing-trial-balance'
    | '/reports/retained-earnings'
    | '/reports/statement-of-cash-flow'
    | '/reports/statement-of-financial-position'
    | '/reports/unadjusted-trial-balance'
    | '/reports/worksheet'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aiassistant'
    | '/_authenticated/chart-of-accounts'
    | '/_authenticated/dashboard'
    | '/_authenticated/guardian'
    | '/_authenticated/home'
    | '/_authenticated/journal-entry'
    | '/_authenticated/periods'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/'
    | '/_authenticated/reports/adjusted-trial-balance'
    | '/_authenticated/reports/adjusting-journal'
    | '/_authenticated/reports/closing-journal'
    | '/_authenticated/reports/general-journal'
    | '/_authenticated/reports/general-ledger-permanent'
    | '/_authenticated/reports/general-ledger-temporary'
    | '/_authenticated/reports/income-statement'
    | '/_authenticated/reports/post-closing-trial-balance'
    | '/_authenticated/reports/retained-earnings'
    | '/_authenticated/reports/statement-of-cash-flow'
    | '/_authenticated/reports/statement-of-financial-position'
    | '/_authenticated/reports/unadjusted-trial-balance'
    | '/_authenticated/reports/worksheet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aiassistant': {
      id: '/_authenticated/aiassistant'
      path: '/aiassistant'
      fullPath: '/aiassistant'
      preLoaderRoute: typeof AuthenticatedAiassistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chart-of-accounts': {
      id: '/_authenticated/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/chart-of-accounts'
      preLoaderRoute: typeof AuthenticatedChartOfAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guardian': {
      id: '/_authenticated/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof AuthenticatedGuardianRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal-entry': {
      id: '/_authenticated/journal-entry'
      path: '/journal-entry'
      fullPath: '/journal-entry'
      preLoaderRoute: typeof AuthenticatedJournalEntryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/periods': {
      id: '/_authenticated/periods'
      path: '/periods'
      fullPath: '/periods'
      preLoaderRoute: typeof AuthenticatedPeriodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/adjusted-trial-balance': {
      id: '/_authenticated/reports/adjusted-trial-balance'
      path: '/reports/adjusted-trial-balance'
      fullPath: '/reports/adjusted-trial-balance'
      preLoaderRoute: typeof AuthenticatedReportsAdjustedTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/adjusting-journal': {
      id: '/_authenticated/reports/adjusting-journal'
      path: '/reports/adjusting-journal'
      fullPath: '/reports/adjusting-journal'
      preLoaderRoute: typeof AuthenticatedReportsAdjustingJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/closing-journal': {
      id: '/_authenticated/reports/closing-journal'
      path: '/reports/closing-journal'
      fullPath: '/reports/closing-journal'
      preLoaderRoute: typeof AuthenticatedReportsClosingJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/general-journal': {
      id: '/_authenticated/reports/general-journal'
      path: '/reports/general-journal'
      fullPath: '/reports/general-journal'
      preLoaderRoute: typeof AuthenticatedReportsGeneralJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/general-ledger-permanent': {
      id: '/_authenticated/reports/general-ledger-permanent'
      path: '/reports/general-ledger-permanent'
      fullPath: '/reports/general-ledger-permanent'
      preLoaderRoute: typeof AuthenticatedReportsGeneralLedgerPermanentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/general-ledger-temporary': {
      id: '/_authenticated/reports/general-ledger-temporary'
      path: '/reports/general-ledger-temporary'
      fullPath: '/reports/general-ledger-temporary'
      preLoaderRoute: typeof AuthenticatedReportsGeneralLedgerTemporaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/income-statement': {
      id: '/_authenticated/reports/income-statement'
      path: '/reports/income-statement'
      fullPath: '/reports/income-statement'
      preLoaderRoute: typeof AuthenticatedReportsIncomeStatementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/post-closing-trial-balance': {
      id: '/_authenticated/reports/post-closing-trial-balance'
      path: '/reports/post-closing-trial-balance'
      fullPath: '/reports/post-closing-trial-balance'
      preLoaderRoute: typeof AuthenticatedReportsPostClosingTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/retained-earnings': {
      id: '/_authenticated/reports/retained-earnings'
      path: '/reports/retained-earnings'
      fullPath: '/reports/retained-earnings'
      preLoaderRoute: typeof AuthenticatedReportsRetainedEarningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/statement-of-cash-flow': {
      id: '/_authenticated/reports/statement-of-cash-flow'
      path: '/reports/statement-of-cash-flow'
      fullPath: '/reports/statement-of-cash-flow'
      preLoaderRoute: typeof AuthenticatedReportsStatementOfCashFlowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/statement-of-financial-position': {
      id: '/_authenticated/reports/statement-of-financial-position'
      path: '/reports/statement-of-financial-position'
      fullPath: '/reports/statement-of-financial-position'
      preLoaderRoute: typeof AuthenticatedReportsStatementOfFinancialPositionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/unadjusted-trial-balance': {
      id: '/_authenticated/reports/unadjusted-trial-balance'
      path: '/reports/unadjusted-trial-balance'
      fullPath: '/reports/unadjusted-trial-balance'
      preLoaderRoute: typeof AuthenticatedReportsUnadjustedTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/worksheet': {
      id: '/_authenticated/reports/worksheet'
      path: '/reports/worksheet'
      fullPath: '/reports/worksheet'
      preLoaderRoute: typeof AuthenticatedReportsWorksheetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiassistantRoute: typeof AuthenticatedAiassistantRoute
  AuthenticatedChartOfAccountsRoute: typeof AuthenticatedChartOfAccountsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGuardianRoute: typeof AuthenticatedGuardianRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJournalEntryRoute: typeof AuthenticatedJournalEntryRoute
  AuthenticatedPeriodsRoute: typeof AuthenticatedPeriodsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedReportsAdjustedTrialBalanceRoute: typeof AuthenticatedReportsAdjustedTrialBalanceRoute
  AuthenticatedReportsAdjustingJournalRoute: typeof AuthenticatedReportsAdjustingJournalRoute
  AuthenticatedReportsClosingJournalRoute: typeof AuthenticatedReportsClosingJournalRoute
  AuthenticatedReportsGeneralJournalRoute: typeof AuthenticatedReportsGeneralJournalRoute
  AuthenticatedReportsGeneralLedgerPermanentRoute: typeof AuthenticatedReportsGeneralLedgerPermanentRoute
  AuthenticatedReportsGeneralLedgerTemporaryRoute: typeof AuthenticatedReportsGeneralLedgerTemporaryRoute
  AuthenticatedReportsIncomeStatementRoute: typeof AuthenticatedReportsIncomeStatementRoute
  AuthenticatedReportsPostClosingTrialBalanceRoute: typeof AuthenticatedReportsPostClosingTrialBalanceRoute
  AuthenticatedReportsRetainedEarningsRoute: typeof AuthenticatedReportsRetainedEarningsRoute
  AuthenticatedReportsStatementOfCashFlowRoute: typeof AuthenticatedReportsStatementOfCashFlowRoute
  AuthenticatedReportsStatementOfFinancialPositionRoute: typeof AuthenticatedReportsStatementOfFinancialPositionRoute
  AuthenticatedReportsUnadjustedTrialBalanceRoute: typeof AuthenticatedReportsUnadjustedTrialBalanceRoute
  AuthenticatedReportsWorksheetRoute: typeof AuthenticatedReportsWorksheetRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiassistantRoute: AuthenticatedAiassistantRoute,
  AuthenticatedChartOfAccountsRoute: AuthenticatedChartOfAccountsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGuardianRoute: AuthenticatedGuardianRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJournalEntryRoute: AuthenticatedJournalEntryRoute,
  AuthenticatedPeriodsRoute: AuthenticatedPeriodsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedReportsAdjustedTrialBalanceRoute:
    AuthenticatedReportsAdjustedTrialBalanceRoute,
  AuthenticatedReportsAdjustingJournalRoute:
    AuthenticatedReportsAdjustingJournalRoute,
  AuthenticatedReportsClosingJournalRoute:
    AuthenticatedReportsClosingJournalRoute,
  AuthenticatedReportsGeneralJournalRoute:
    AuthenticatedReportsGeneralJournalRoute,
  AuthenticatedReportsGeneralLedgerPermanentRoute:
    AuthenticatedReportsGeneralLedgerPermanentRoute,
  AuthenticatedReportsGeneralLedgerTemporaryRoute:
    AuthenticatedReportsGeneralLedgerTemporaryRoute,
  AuthenticatedReportsIncomeStatementRoute:
    AuthenticatedReportsIncomeStatementRoute,
  AuthenticatedReportsPostClosingTrialBalanceRoute:
    AuthenticatedReportsPostClosingTrialBalanceRoute,
  AuthenticatedReportsRetainedEarningsRoute:
    AuthenticatedReportsRetainedEarningsRoute,
  AuthenticatedReportsStatementOfCashFlowRoute:
    AuthenticatedReportsStatementOfCashFlowRoute,
  AuthenticatedReportsStatementOfFinancialPositionRoute:
    AuthenticatedReportsStatementOfFinancialPositionRoute,
  AuthenticatedReportsUnadjustedTrialBalanceRoute:
    AuthenticatedReportsUnadjustedTrialBalanceRoute,
  AuthenticatedReportsWorksheetRoute: AuthenticatedReportsWorksheetRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
